Repository quicktype/quicktype, pull requests merged in 2018-02, with the labels that each got.

#539 Parenthesize TS unions correctly. Fixes #523
  src/ConvenienceRenderer.ts
  src/Language/Elm.ts
  src/Language/TypeScript.ts
  src/Source.ts
Labels: typescript

#542 Ensure a space between attribute and property in dense mode
  src/Language/CSharp.ts
Labels: C#

#538 Header comment compacted, fix invalid JSON in header
  src/Language/Rust.ts
Labels: rust

#554 Emit descriptions in C#
  src/Language/CSharp.ts
Labels: C#

#555 Name C# sample variables according to top-level name
  src/Language/CSharp.ts
Labels: C#

#558 Massive test speedups for Rust, Elm, and Java
  .gitignore
  Dockerfile
  test/fixtures/java/src/main/java/io/quicktype/Converter.java
  test/fixtures/java/src/main/java/io/quicktype/TopLevel.java
  test/fixtures/rust/Cargo.toml
  test/languages.ts
Labels: rust

#560 Name references in sample code according to top-level names
  src/Language/Golang.ts
Labels: go

#540 DateTime serialization and deserialization uses UTC if no timezone specified
  src/Language/CSharp.ts
Labels: C#

#592 Experimental Flow support
  .buildkite/pipeline.yml
  package.json
  src/Language/All.ts
  src/Language/JavaScript.ts
  src/Language/TypeScriptFlow.ts
  test/fixtures.ts
  test/fixtures/flow/.flowconfig
  test/fixtures/flow/main.js
  test/languages.ts
Labels: Flow
